language: node_js

node_js:
  - "8.11"

cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
env:
  - TRAVIS_BUILD=true

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  github-token: $GITHUB_TOKEN
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    branch: master

