language: node_js

node_js:
  - "8.11"

notifications:
  email: false

script: gulp build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: lXkqTKcP70z66H4pKkVc6g
  keep-history: true
  on:
    branch: master

