language: node_js

node_js:
  - "8.11"

script:
  - npm run ci
  - npm run build

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master


